### ISSUE TITLE
Updating this feedstock -- Conda build fails on Mac os 10.14

### ISSUE THREAD

**Issue by ddesmond** [conda-forge/openimageio-feedstock#57]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Trying to build openimageio from the feedstock recipe yields:
`
-- Configuring incomplete, errors occurred!
See also "$SRC_DIR/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/Users/des/miniconda3/envs/conda_usd_build/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/des/miniconda3/envs/conda_usd_build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "/Users/des/miniconda3/envs/conda_usd_build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 479, in execute
    verify=args.verify, variants=args.variants, cache_dir=args.cache_dir)
  File "/Users/des/miniconda3/envs/conda_usd_build/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/Users/des/miniconda3/envs/conda_usd_build/lib/python3.7/site-packages/conda_build/build.py", line 3093, in build_tree
    notest=notest,
  File "/Users/des/miniconda3/envs/conda_usd_build/lib/python3.7/site-packages/conda_build/build.py", line 2212, in build
    cwd=src_dir, stats=build_stats)
  File "/Users/des/miniconda3/envs/conda_usd_build/lib/python3.7/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/des/miniconda3/envs/conda_usd_build/lib/python3.7/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/des/miniconda3/envs/conda_usd_build/conda-bld/openimageio_1647586659186/work/conda_build.sh']' returned non-zero exit status 1.
(conda_usd_build) mbp-dev:openimageio-feedstock des$ 
`

### Installed packages

```shell
(conda_usd_build) mbp-dev:openimageio-feedstock des$ conda list
# packages in environment at /Users/des/miniconda3/envs/conda_usd_build:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
boost                     1.77.0           py37h326c9ff_0    conda-forge
boost-cpp                 1.77.0               hf3dc895_1    conda-forge
brotlipy                  0.7.0           py37h271585c_1003    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py37hf985489_1    conda-forge
cffi                      1.15.0           py37h446072c_0    conda-forge
chardet                   4.0.0            py37hf985489_2    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py37hf985489_0    conda-forge
conda-build               3.21.8           py37hf985489_0    conda-forge
conda-package-handling    1.8.0            py37h69ee0a8_0    conda-forge
cryptography              36.0.1           py37h5e77fcc_0    conda-forge
curl                      7.82.0               h9f20792_0    conda-forge
expat                     2.4.7                h96cf925_0    conda-forge
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
git                       2.35.1          pl5321h33a4a8a_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0d85af4_0    conda-forge
krb5                      1.19.2               hb49756b_4    conda-forge
libarchive                3.5.2                h2b60450_1    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libclang                  13.0.1          default_he082bbe_0    conda-forge
libcurl                   7.82.0               h9f20792_0    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
liblief                   0.11.5               he49afe7_1    conda-forge
libllvm13                 13.0.1               h64f94b2_2    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     14.2                 hea3049e_0    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libxslt                   1.1.33               h1acebb3_3    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
lzo                       2.10              haf1e3a3_1000    conda-forge
markupsafe                2.1.0            py37h69ee0a8_1    conda-forge
mysql-common              8.0.28               h694c41f_0    conda-forge
mysql-libs                8.0.28               h115446f_0    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
nspr                      4.32                 hcd9eead_1    conda-forge
```

### Environment info

```shell
(conda_usd_build) mbp-dev:openimageio-feedstock des$ conda info

     active environment : conda_usd_build
    active env location : /Users/des/miniconda3/envs/conda_usd_build
            shell level : 1
       user config file : /Users/des/.condarc
 populated config files : /Users/des/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __osx=10.14.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/des/miniconda3  (writable)
      conda av data dir : /Users/des/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/des/miniconda3/pkgs
                          /Users/des/.conda/pkgs
       envs directories : /Users/des/miniconda3/envs
                          /Users/des/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.10 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by hmaarrfk** [comment]
This recipe likely needs some love. 

I've tried to update the version, but I don't know how to get it to stop detecting system libs.

I don't really use this library, so I don't have too much more time to spend on this, but you might want to continue from:
https://github.com/conda-forge/openimageio-feedstock/pull/75

and update as needed and issue a PR with your progress.

**Comment by hmaarrfk** [comment]
You might find the patch in https://github.com/conda-forge/freeimage-feedstock/pull/35 useful for libraw 0.21
